# Generated by Django 3.1 on 2020-08-15 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_api', '0004_phoneotp_validated'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='ProfileFeedItem',
        ),
    ]
