# Generated by Django 3.1 on 2020-08-15 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_api', '0005_auto_20200815_0612'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('providerName', models.CharField(max_length=255)),
                ('providerFirstName', models.CharField(max_length=255)),
                ('short_description', models.CharField(max_length=255)),
                ('rating', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_api.servicecategories')),
            ],
        ),
    ]
