# Generated by Django 3.1 on 2020-08-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_api', '0006_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='lat',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='service',
            name='lon',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=12),
        ),
    ]
