# Generated by Django 3.1 on 2020-08-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_api', '0008_userprofile_following_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='following_services',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
