# Generated by Django 3.1 on 2020-08-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_api', '0011_auto_20200816_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='following_services',
            field=models.CharField(default='', max_length=255),
        ),
    ]
