# Generated by Django 3.1 on 2020-09-19 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_api', '0013_auto_20200816_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
    ]
