# Generated by Django 3.1 on 2020-09-19 12:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_api', '0014_remove_userprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(default='0000000000', max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be in format. upto 14 digits allowed.', regex='^\\+?1?\\d{9,14}$')]),
        ),
    ]
